In [17]:
import numpy as np
with open("argR-counts-matrix.txt", "r") as f:
    lines = f.readlines()
# Initialize an empty list
counts = []
# Loop through the lines in the input file
for line in lines:
    # Split the line by the "|" character
    line = line.strip().split("|")[1]

    # Convert the numbers to integers and add them to the list
    counts.append([int(x) for x in line.split()])
counts = np.array(counts)
counts

array([[ 8, 12, 21,  9,  4,  2, 21, 21,  3, 10,  8,  5,  7, 25,  4,  2,
         2, 25],
       [ 7,  4,  1,  6,  2,  3,  3,  3,  1,  0,  2,  0,  7,  0,  3,  3,
        24,  0],
       [ 3,  2,  1,  8,  2, 21,  2,  2,  0,  1,  0,  1,  0,  1,  0, 15,
         0,  2],
       [ 9,  9,  4,  4, 19,  1,  1,  1, 23, 16, 17, 21, 13,  1, 20,  7,
         1,  0]])

In [18]:
pseudo_counts_matrix = counts + 1
pseudo_counts_matrix

array([[ 9, 13, 22, 10,  5,  3, 22, 22,  4, 11,  9,  6,  8, 26,  5,  3,
         3, 26],
       [ 8,  5,  2,  7,  3,  4,  4,  4,  2,  1,  3,  1,  8,  1,  4,  4,
        25,  1],
       [ 4,  3,  2,  9,  3, 22,  3,  3,  1,  2,  1,  2,  1,  2,  1, 16,
         1,  3],
       [10, 10,  5,  5, 20,  2,  2,  2, 24, 17, 18, 22, 14,  2, 21,  8,
         2,  1]])

In [19]:
total_counts = np.sum(pseudo_counts_matrix, axis=0)
# Calculate the frequency matrix
freq_matrix = pseudo_counts_matrix / total_counts
print("Frequency matrix shape:", freq_matrix.shape)
freq_matrix

Frequency matrix shape: (4, 18)


array([[0.29032258, 0.41935484, 0.70967742, 0.32258065, 0.16129032,
        0.09677419, 0.70967742, 0.70967742, 0.12903226, 0.35483871,
        0.29032258, 0.19354839, 0.25806452, 0.83870968, 0.16129032,
        0.09677419, 0.09677419, 0.83870968],
       [0.25806452, 0.16129032, 0.06451613, 0.22580645, 0.09677419,
        0.12903226, 0.12903226, 0.12903226, 0.06451613, 0.03225806,
        0.09677419, 0.03225806, 0.25806452, 0.03225806, 0.12903226,
        0.12903226, 0.80645161, 0.03225806],
       [0.12903226, 0.09677419, 0.06451613, 0.29032258, 0.09677419,
        0.70967742, 0.09677419, 0.09677419, 0.03225806, 0.06451613,
        0.03225806, 0.06451613, 0.03225806, 0.06451613, 0.03225806,
        0.51612903, 0.03225806, 0.09677419],
       [0.32258065, 0.32258065, 0.16129032, 0.16129032, 0.64516129,
        0.06451613, 0.06451613, 0.06451613, 0.77419355, 0.5483871 ,
        0.58064516, 0.70967742, 0.4516129 , 0.06451613, 0.67741935,
        0.25806452, 0.06451613, 0.03225806]])

In [20]:
pwm = np.log2(freq_matrix/0.25)
print("Weight matrix shape:", pwm.shape)
pwm

Weight matrix shape: (4, 18)


array([[ 0.21572869,  0.74624341,  1.50523531,  0.36773178, -0.63226822,
        -1.36923381,  1.50523531,  1.50523531, -0.95419631,  0.50523531,
         0.21572869, -0.36923381,  0.04580369,  1.74624341, -0.63226822,
        -1.36923381, -1.36923381,  1.74624341],
       [ 0.04580369, -0.63226822, -1.95419631, -0.14684139, -1.36923381,
        -0.95419631, -0.95419631, -0.95419631, -1.95419631, -2.95419631,
        -1.36923381, -2.95419631,  0.04580369, -2.95419631, -0.95419631,
        -0.95419631,  1.68965988, -2.95419631],
       [-0.95419631, -1.36923381, -1.95419631,  0.21572869, -1.36923381,
         1.50523531, -1.36923381, -1.36923381, -2.95419631, -1.95419631,
        -2.95419631, -1.95419631, -2.95419631, -1.95419631, -2.95419631,
         1.04580369, -2.95419631, -1.36923381],
       [ 0.36773178,  0.36773178, -0.63226822, -0.63226822,  1.36773178,
        -1.95419631, -1.95419631, -1.95419631,  1.63076619,  1.13326653,
         1.21572869,  1.50523531,  0.85315861, -1.954

In [21]:
import pandas as pd
df_gene_seq = pd.read_csv(r'E_coli_K12_MG1655.400_50\\E_coli_K12_MG1655.400_50', sep = "\\", header = None)
df_gene_seq.rename(columns={0: 'gene_id', 1: 'sequence'}, inplace=True)
df_gene_seq.drop(columns=2, inplace = True)
# create an empty list to store the extracted sequences and gene_ids
sequences = []
gene_ids = []

# iterate over each row in the DataFrame
for index, row in df_gene_seq.iterrows():
    # extract the sequence of length 450 from the sequence column
    sequence = row['sequence'][:450]
    # append the extracted sequence and gene_id to their respective lists
    sequences.append(sequence)
    gene_ids.append(row['gene_id'])

# create a new DataFrame with the gene_id and extracted sequences
new_df = pd.DataFrame({'gene_id': gene_ids, 'sequence': sequences})
print(new_df)

        gene_id                                           sequence
0     16127995    aacggcagaccaacatcaactgcaagctttacgcgaacgagccat...
1     16127996    ccgtttgctgcatgatattgaaaaaaatatcaccaaataaaaaac...
2     16127997    gaaacgggacgtgaactggagctggcggatattgaaattgaacct...
3     16127998    ggggattaaagtctcgacggcagaagccagggctattttaccggc...
4     16127999    aggcgaatatggcttgttcctcggcaccgcgcatccggcgaaatt...
...         ...                                                ...
4314  16132216    gtgctgacgactacgtggctaaaccgttttcaccccgcgaagtgt...
4315  16132217    tgctgctgaaccggcgttactggagcaggcgctgggaaatttact...
4316  16132218    acgtttattagttgtatgatgcaactagttggattattaaaataa...
4317  16132219    gtgatgtagtcatctgcaccgatttcgaggccgagaattttatcg...
4318  16132220    acaggctaagaggggccggacacccaataaaactacgcttcgttg...

[4319 rows x 2 columns]


In [24]:
window_size = len(pwm[0])

# Compute the PWM scores for each sequence
top_scores = []
for i in range(len(new_df)):
    seq = new_df.iloc[i]['sequence']
    scores = []
    for j in range(len(seq) - window_size + 1):
        subseq = seq[j:j+window_size]
        score = 0
        for k in range(window_size):
            base = subseq[k]
            if base == 'a':
                score += pwm[0][k]
            elif base == 'c':
                score += pwm[1][k]
            elif base == 'g':
                score += pwm[2][k]
            elif base == 't':
                score += pwm[3][k]
        scores.append(score)
    top_score = max(scores)
    top_scores.append((new_df.iloc[i]['gene_id'], top_score))

# Sort the top scores in descending order and get the top 30 scores
sorted_scores = sorted(top_scores, key=lambda x: x[1], reverse=True)[:30]

# Print the gene IDs corresponding to the top scores
for gene_id, score in sorted_scores:
    print(f"Gene ID: {gene_id}")

Gene ID: b3171 
Gene ID: 16128258 
Gene ID: 16132076 
Gene ID: 16131126 
Gene ID: 16131238 
Gene ID: 16129301 
Gene ID: 16128684 
Gene ID: 16130583 
Gene ID: 16131795 
Gene ID: 16128026 
Gene ID: 16129126 
Gene ID: 49176132 
Gene ID: 16132077 
Gene ID: 16128462 
Gene ID: 16131312 
Gene ID: b4451 
Gene ID: 16128105 
Gene ID: 16131247 
Gene ID: 16131392 
Gene ID: 16131884 
Gene ID: 16128650 
Gene ID: 16129601 
Gene ID: 90111311 
Gene ID: 90111175 
Gene ID: 16132166 
Gene ID: 90111703 
Gene ID: 16128795 
Gene ID: 16128628 
Gene ID: 16128106 
Gene ID: 90111372 
